import type { MasterEntityKey } from "@/types/domain";
import type { MasterEntityConfig } from "@/modules/master/types";

export const masterEntityConfig: Record<MasterEntityKey, MasterEntityConfig> = {
  farmers: {
    key: "farmers",
    title: "Farmers",
    singular: "Farmer",
    description: "Kelola data petani pemasok TBS",
    createLabel: "Tambah Farmer",
    editLabel: "Simpan Perubahan",
    detailTitle: "Detail Farmer",
    searchablePlaceholder: "Cari kode, nama, telepon, desa, kota...",
    supportsStatusToggle: true,
    listColumns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "phone", label: "Phone" },
      { key: "location", label: "Village/City", type: "location" },
      { key: "outstandingAmount", label: "Sisa Hutang Petani", type: "currency" },
      { key: "storeReceivableOutstanding", label: "Hutang Toko", type: "currency" },
      { key: "isActive", label: "Status", type: "status" },
      { key: "createdAt", label: "Created At", type: "date" },
    ],
    detailFields: [
      "code",
      "name",
      "phone",
      "address",
      "village",
      "districtOrCity",
      "outstandingAmount",
      "storeReceivableOutstanding",
      "notes",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    formSections: [
      {
        key: "main",
        title: "Informasi Utama",
        fields: [
          { name: "code", label: "Code", type: "text", required: true },
          { name: "name", label: "Name", type: "text", required: true },
          { name: "isActive", label: "Aktif", type: "switch" },
        ],
      },
      {
        key: "contact",
        title: "Kontak",
        fields: [{ name: "phone", label: "Phone", type: "text" }],
      },
      {
        key: "address",
        title: "Alamat",
        fields: [
          { name: "address", label: "Address", type: "textarea" },
          { name: "village", label: "Village", type: "text" },
          { name: "districtOrCity", label: "District / City", type: "text" },
        ],
      },
      {
        key: "notes",
        title: "Catatan",
        fields: [{ name: "notes", label: "Notes", type: "textarea" }],
      },
    ],
    defaultValues: {
      code: "",
      name: "",
      phone: "",
      address: "",
      village: "",
      districtOrCity: "",
      notes: "",
      isActive: true,
    },
  },
  factories: {
    key: "factories",
    title: "Factories",
    singular: "Factory",
    description: "Kelola data pabrik tujuan penjualan TBS",
    createLabel: "Tambah Factory",
    editLabel: "Simpan Perubahan",
    detailTitle: "Detail Factory",
    searchablePlaceholder: "Cari kode, nama, telepon, kota...",
    supportsStatusToggle: true,
    listColumns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "phone", label: "Phone" },
      { key: "city", label: "City" },
      { key: "isActive", label: "Status", type: "status" },
      { key: "createdAt", label: "Created At", type: "date" },
    ],
    detailFields: ["code", "name", "phone", "email", "address", "city", "contactPerson", "notes", "isActive", "createdAt", "updatedAt"],
    formSections: [
      {
        key: "main",
        title: "Informasi Utama",
        fields: [
          { name: "code", label: "Code", type: "text", required: true },
          { name: "name", label: "Name", type: "text", required: true },
          { name: "contactPerson", label: "Contact Person", type: "text" },
          { name: "isActive", label: "Aktif", type: "switch" },
        ],
      },
      {
        key: "contact",
        title: "Kontak",
        fields: [
          { name: "phone", label: "Phone", type: "text" },
          { name: "email", label: "Email", type: "email" },
        ],
      },
      {
        key: "address",
        title: "Alamat",
        fields: [
          { name: "address", label: "Address", type: "textarea" },
          { name: "city", label: "City", type: "text" },
        ],
      },
      {
        key: "notes",
        title: "Catatan",
        fields: [{ name: "notes", label: "Notes", type: "textarea" }],
      },
    ],
    defaultValues: { code: "", name: "", contactPerson: "", phone: "", email: "", address: "", city: "", notes: "", isActive: true },
  },
  customers: {
    key: "customers",
    title: "Pelanggan Toko",
    singular: "Pelanggan Toko",
    description:
      "Kelola pelanggan toko pertanian. Jika pelanggan yang sama juga merupakan petani, tautkan ke data petani agar piutang toko bisa dipotong dari hasil TBS.",
    createLabel: "Tambah Pelanggan Toko",
    editLabel: "Simpan Perubahan",
    detailTitle: "Detail Pelanggan Toko",
    searchablePlaceholder: "Cari kode, nama, telepon, kota, atau petani terkait...",
    supportsStatusToggle: true,
    listColumns: [
      { key: "code", label: "Kode" },
      { key: "name", label: "Nama Pelanggan" },
      { key: "farmerName", label: "Petani Terkait" },
      { key: "phone", label: "No HP" },
      { key: "city", label: "Kota" },
      { key: "isActive", label: "Status", type: "status" },
      { key: "createdAt", label: "Dibuat Pada", type: "date" },
    ],
    detailFields: [
      "code",
      "name",
      "farmerName",
      "farmerCode",
      "phone",
      "email",
      "address",
      "city",
      "contactPerson",
      "notes",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    formSections: [
      {
        key: "main",
        title: "Informasi Utama",
        fields: [
          { name: "code", label: "Kode", type: "text", required: true },
          { name: "name", label: "Nama Pelanggan", type: "text", required: true },
          {
            name: "isFarmer",
            label: "Ini Petani",
            type: "switch",
            description: "Otomatis buat/tautkan data petani agar piutang bisa dipotong dari hasil TBS.",
          },
          {
            name: "farmerId",
            label: "Petani Terkait (Opsional)",
            type: "select",
            optionsSource: "farmers",
          },
          { name: "isActive", label: "Aktif", type: "switch" },
        ],
      },
      {
        key: "contact",
        title: "Kontak",
        fields: [
          { name: "phone", label: "No HP", type: "text" },
          { name: "email", label: "Email", type: "email" },
        ],
      },
      {
        key: "address",
        title: "Alamat",
        fields: [
          { name: "address", label: "Alamat", type: "textarea" },
          { name: "city", label: "Kota", type: "text" },
        ],
      },
      {
        key: "notes",
        title: "Catatan",
        fields: [{ name: "notes", label: "Notes", type: "textarea" }],
      },
    ],
    defaultValues: {
      code: "",
      name: "",
      farmerId: "",
      isFarmer: false,
      phone: "",
      email: "",
      address: "",
      city: "",
      notes: "",
      isActive: true,
    },
  },
  suppliers: {
    key: "suppliers",
    title: "Suppliers",
    singular: "Supplier",
    description: "Kelola supplier produk toko",
    createLabel: "Tambah Supplier",
    editLabel: "Simpan Perubahan",
    detailTitle: "Detail Supplier",
    searchablePlaceholder: "Cari kode, nama, telepon, kota...",
    supportsStatusToggle: true,
    listColumns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "phone", label: "Phone" },
      { key: "city", label: "City" },
      { key: "isActive", label: "Status", type: "status" },
      { key: "createdAt", label: "Created At", type: "date" },
    ],
    detailFields: ["code", "name", "phone", "email", "address", "city", "contactPerson", "notes", "isActive", "createdAt", "updatedAt"],
    formSections: [
      {
        key: "main",
        title: "Informasi Utama",
        fields: [
          { name: "code", label: "Code", type: "text", required: true },
          { name: "name", label: "Name", type: "text", required: true },
          { name: "contactPerson", label: "Contact Person", type: "text" },
          { name: "isActive", label: "Aktif", type: "switch" },
        ],
      },
      {
        key: "contact",
        title: "Kontak",
        fields: [
          { name: "phone", label: "Phone", type: "text" },
          { name: "email", label: "Email", type: "email" },
        ],
      },
      {
        key: "address",
        title: "Alamat",
        fields: [
          { name: "address", label: "Address", type: "textarea" },
          { name: "city", label: "City", type: "text" },
        ],
      },
      {
        key: "notes",
        title: "Catatan",
        fields: [{ name: "notes", label: "Notes", type: "textarea" }],
      },
    ],
    defaultValues: { code: "", name: "", contactPerson: "", phone: "", email: "", address: "", city: "", notes: "", isActive: true },
  },
  "transport-personnel": {
    key: "transport-personnel",
    title: "Personel Armada",
    singular: "Personel Armada",
    description: "Sumber tunggal data sopir, kernet, dan helper untuk transaksi TBS, trip, dan surat jalan",
    createLabel: "Tambah Personel Armada",
    editLabel: "Simpan Perubahan",
    detailTitle: "Detail Personel Armada",
    searchablePlaceholder: "Cari kode, nama, peran, no HP, no SIM, no identitas...",
    supportsStatusToggle: true,
    listColumns: [
      { key: "code", label: "Kode" },
      { key: "name", label: "Nama" },
      { key: "roleLabel", label: "Peran" },
      { key: "phone", label: "No HP" },
      { key: "licenseNumber", label: "No SIM" },
      { key: "identityNumber", label: "No Identitas" },
      { key: "primaryVehicleLabel", label: "Kendaraan Utama" },
      { key: "isActive", label: "Status", type: "status" },
    ],
    detailFields: [
      "code",
      "name",
      "roleLabel",
      "phone",
      "licenseNumber",
      "identityNumber",
      "primaryVehicleLabel",
      "notes",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    formSections: [
      {
        key: "main",
        title: "Informasi Utama",
        fields: [
          { name: "code", label: "Kode", type: "text", required: true },
          {
            name: "role",
            label: "Peran",
            type: "select",
            required: true,
            options: [
              { value: "driver", label: "Sopir" },
              { value: "co_driver", label: "Kernet" },
              { value: "helper", label: "Helper" },
            ],
          },
          { name: "name", label: "Nama", type: "text", required: true },
          { name: "isActive", label: "Aktif", type: "switch" },
        ],
      },
      {
        key: "contact",
        title: "Kontak & Identitas",
        fields: [
          { name: "phone", label: "No HP", type: "text" },
          { name: "licenseNumber", label: "No SIM", type: "text" },
          { name: "identityNumber", label: "No Identitas", type: "text" },
        ],
      },
      {
        key: "vehicle",
        title: "Relasi Kendaraan",
        description: "Kendaraan utama bersifat opsional dan hanya untuk referensi awal sebelum modul trip aktif.",
        fields: [
          {
            name: "primaryVehicleId",
            label: "Kendaraan Utama",
            type: "select",
            optionsSource: "vehicles",
          },
        ],
      },
      {
        key: "notes",
        title: "Catatan",
        fields: [{ name: "notes", label: "Catatan", type: "textarea" }],
      },
    ],
    defaultValues: {
      code: "",
      role: "driver",
      name: "",
      phone: "",
      licenseNumber: "",
      identityNumber: "",
      primaryVehicleId: "",
      notes: "",
      isActive: true,
    },
  },
  vehicles: {
    key: "vehicles",
    title: "Vehicles",
    singular: "Vehicle",
    description: "Kelola armada kendaraan operasional",
    createLabel: "Tambah Vehicle",
    editLabel: "Simpan Perubahan",
    detailTitle: "Detail Vehicle",
    searchablePlaceholder: "Cari kode, plat nomor, tipe...",
    supportsStatusToggle: true,
    listColumns: [
      { key: "code", label: "Code" },
      { key: "plateNumber", label: "Plate Number" },
      { key: "type", label: "Type" },
      { key: "capacityKg", label: "Capacity", type: "number" },
      { key: "isActive", label: "Status", type: "status" },
      { key: "createdAt", label: "Created At", type: "date" },
    ],
    detailFields: ["code", "plateNumber", "type", "capacityKg", "notes", "isActive", "createdAt", "updatedAt"],
    formSections: [
      {
        key: "main",
        title: "Informasi Utama",
        fields: [
          { name: "code", label: "Code", type: "text", required: true },
          { name: "plateNumber", label: "Plate Number", type: "text", required: true },
          { name: "type", label: "Type", type: "text" },
          { name: "capacityKg", label: "Capacity (Kg)", type: "number" },
          { name: "isActive", label: "Aktif", type: "switch" },
        ],
      },
      {
        key: "notes",
        title: "Catatan",
        fields: [{ name: "notes", label: "Notes", type: "textarea" }],
      },
    ],
    defaultValues: { code: "", plateNumber: "", type: "", capacityKg: 0, notes: "", isActive: true },
  },
  warehouses: {
    key: "warehouses",
    title: "Warehouses",
    singular: "Warehouse",
    description: "Kelola gudang operasional sawit dan toko",
    createLabel: "Tambah Warehouse",
    editLabel: "Simpan Perubahan",
    detailTitle: "Detail Warehouse",
    searchablePlaceholder: "Cari kode, nama, alamat...",
    supportsStatusToggle: true,
    listColumns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "address", label: "Address" },
      { key: "isActive", label: "Status", type: "status" },
      { key: "createdAt", label: "Created At", type: "date" },
    ],
    detailFields: ["code", "name", "address", "notes", "isActive", "createdAt", "updatedAt"],
    formSections: [
      {
        key: "main",
        title: "Informasi Utama",
        fields: [
          { name: "code", label: "Code", type: "text", required: true },
          { name: "name", label: "Name", type: "text", required: true },
          { name: "isActive", label: "Aktif", type: "switch" },
        ],
      },
      {
        key: "address",
        title: "Alamat",
        fields: [{ name: "address", label: "Address", type: "textarea" }],
      },
      {
        key: "notes",
        title: "Catatan",
        fields: [{ name: "notes", label: "Notes", type: "textarea" }],
      },
    ],
    defaultValues: { code: "", name: "", address: "", notes: "", isActive: true },
  },
  products: {
    key: "products",
    title: "Produk",
    singular: "Produk",
    description: "Kelola SKU, harga aktif, dan stok minimum toko",
    createLabel: "Tambah Produk",
    editLabel: "Simpan Perubahan",
    detailTitle: "Detail Produk",
    searchablePlaceholder: "Cari kode, SKU, nama produk...",
    supportsStatusToggle: true,
    listColumns: [
      { key: "code", label: "Kode" },
      { key: "name", label: "Nama Produk" },
      { key: "unit", label: "Satuan" },
      { key: "purchasePrice", label: "Harga Beli Aktif", type: "currency" },
      { key: "sellingPrice", label: "Harga Jual Aktif", type: "currency" },
      { key: "isActive", label: "Status", type: "status" },
      { key: "createdAt", label: "Dibuat Pada", type: "date" },
    ],
    detailFields: ["code", "sku", "name", "unit", "purchasePrice", "sellingPrice", "minStock", "allowNegativeStock", "notes", "isActive", "createdAt", "updatedAt"],
    formSections: [
      {
        key: "main",
        title: "Informasi Utama",
        fields: [
          { name: "categoryId", label: "Kategori", type: "select", optionsSource: "categories" },
          { name: "code", label: "Kode", type: "text", required: true },
          { name: "sku", label: "SKU", type: "text" },
          { name: "name", label: "Nama Produk", type: "text", required: true },
          { name: "unit", label: "Satuan", type: "text", required: true },
          { name: "isActive", label: "Aktif", type: "switch" },
        ],
      },
      {
        key: "pricing",
        title: "Harga & Stok",
        fields: [
          { name: "purchasePrice", label: "Harga Beli", type: "number" },
          { name: "sellingPrice", label: "Harga Jual", type: "number" },
          { name: "priceEffectiveFrom", label: "Tanggal Berlaku", type: "date" },
          { name: "priceChangeNote", label: "Catatan Perubahan Harga", type: "textarea" },
          { name: "minStock", label: "Stok Minimum", type: "number" },
          { name: "allowNegativeStock", label: "Izinkan Stok Minus", type: "switch" },
        ],
      },
      {
        key: "notes",
        title: "Catatan",
        fields: [{ name: "notes", label: "Catatan Produk", type: "textarea" }],
      },
    ],
    defaultValues: { categoryId: "", code: "", sku: "", name: "", unit: "", purchasePrice: 0, sellingPrice: 0, priceEffectiveFrom: "", priceChangeNote: "", minStock: 0, allowNegativeStock: false, notes: "", isActive: true },
  },
  categories: {
    key: "categories",
    title: "Categories",
    singular: "Category",
    description: "Kelola kategori produk toko",
    createLabel: "Tambah Category",
    editLabel: "Simpan Perubahan",
    detailTitle: "Detail Category",
    searchablePlaceholder: "Cari kode dan nama kategori...",
    supportsStatusToggle: true,
    listColumns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "description", label: "Description" },
      { key: "isActive", label: "Status", type: "status" },
      { key: "createdAt", label: "Created At", type: "date" },
    ],
    detailFields: ["code", "name", "description", "isActive", "createdAt", "updatedAt"],
    formSections: [
      {
        key: "main",
        title: "Informasi Utama",
        fields: [
          { name: "code", label: "Code", type: "text", required: true },
          { name: "name", label: "Name", type: "text", required: true },
          { name: "isActive", label: "Aktif", type: "switch" },
        ],
      },
      {
        key: "notes",
        title: "Deskripsi",
        fields: [{ name: "description", label: "Description", type: "textarea" }],
      },
    ],
    defaultValues: { code: "", name: "", description: "", isActive: true },
  },
  users: {
    key: "users",
    title: "Users",
    singular: "User",
    description: "Kelola akun pengguna dan peran akses",
    createLabel: "Tambah User",
    editLabel: "Simpan Perubahan",
    detailTitle: "Detail User",
    searchablePlaceholder: "Cari nama, email, telepon...",
    supportsStatusToggle: true,
    listColumns: [
      { key: "fullName", label: "Name" },
      { key: "email", label: "Email" },
      { key: "roleName", label: "Role" },
      { key: "isActive", label: "Status", type: "status" },
      { key: "createdAt", label: "Created At", type: "date" },
    ],
    detailFields: ["fullName", "email", "phone", "roleName", "isActive", "createdAt", "updatedAt"],
    formSections: [
      {
        key: "main",
        title: "Informasi Utama",
        fields: [
          { name: "fullName", label: "Full Name", type: "text", required: true },
          { name: "email", label: "Email", type: "email", required: true },
          { name: "roleId", label: "Role", type: "select", required: true, optionsSource: "roles" },
          { name: "isActive", label: "Aktif", type: "switch" },
        ],
      },
      {
        key: "contact",
        title: "Kontak",
        fields: [{ name: "phone", label: "Phone", type: "text" }],
      },
      {
        key: "security",
        title: "Akses",
        fields: [{ name: "password", label: "Password", type: "password" }],
      },
    ],
    defaultValues: { fullName: "", email: "", roleId: "", phone: "", password: "", isActive: true },
  },
  roles: {
    key: "roles",
    title: "Roles",
    singular: "Role",
    description: "Kelola role dan permission sistem",
    createLabel: "Tambah Role",
    editLabel: "Simpan Perubahan",
    detailTitle: "Detail Role",
    searchablePlaceholder: "Cari kode dan nama role...",
    supportsStatusToggle: false,
    listColumns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "description", label: "Description" },
      { key: "permissionCount", label: "Akses Menu", type: "number" },
      { key: "isSystem", label: "System", type: "boolean" },
      { key: "createdAt", label: "Created At", type: "date" },
    ],
    detailFields: ["code", "name", "description", "isSystem", "permissions", "createdAt", "updatedAt"],
    formSections: [
      {
        key: "main",
        title: "Informasi Utama",
        fields: [
          { name: "code", label: "Code", type: "text", required: true },
          { name: "name", label: "Name", type: "text", required: true },
          { name: "isSystem", label: "System Role", type: "switch" },
        ],
      },
      {
        key: "notes",
        title: "Deskripsi",
        fields: [
          { name: "description", label: "Description", type: "textarea" },
        ],
      },
      {
        key: "permissions",
        title: "Akses Menu",
        description: "Checklist menu yang boleh diakses oleh role ini.",
        fields: [{ name: "permissions", label: "Hak Akses Menu", type: "permissions" }],
      },
    ],
    defaultValues: { code: "", name: "", description: "", permissions: {}, isSystem: false },
  },
};
